base_url = "https://example.com"
title = "My Blog"
compile_sass = true
build_search_index = false

taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true }
]

[extra]
